import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/layouts/Header/Header";
import { Providers } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "3000i",
    description: "Generated by create next app",
    icons: "/3000i_logo_transparent_100x100.png",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Header />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
